# 1.create a 3X3 array with random values.

In [11]:
import numpy as np
random_array = np.random.rand(3, 3)
print(random_array)


[[0.23855392 0.84538838 0.59466363]
 [0.31794013 0.06993865 0.81460279]
 [0.6023106  0.14243432 0.86027903]]


# 2.create a 5X5 matrix with values 1,2,3,4 just below the diagonal

In [12]:
array = np.zeros((5, 5))
np.fill_diagonal(array[1:], [1, 2, 3, 4])
print(array)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.create a 8X8 matrix and fill it wth the checkerboard pattern.

In [13]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  
checkerboard[::2, 1::2] = 1  

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4.normalize a 5X5 random matrix.

In [14]:
random_matrix = np.random.rand(5, 5)

mean = np.mean(random_matrix)
std = np.std(random_matrix)
normalized_matrix = (random_matrix - mean) / std

print("Original Random Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Random Matrix:
[[0.11472267 0.04719811 0.32021606 0.76160321 0.40228988]
 [0.27154108 0.56697581 0.42775825 0.46692864 0.3201412 ]
 [0.80943803 0.33577677 0.00890925 0.95722921 0.33927985]
 [0.65729172 0.03085183 0.37661723 0.04104372 0.512174  ]
 [0.32803619 0.74635815 0.86642793 0.86094876 0.28274169]]

Normalized Matrix:
[[-1.15179477 -1.39531377 -0.41070825  1.18109996 -0.11471916]
 [-0.58624855  0.47920029 -0.02287062  0.11839254 -0.4109782 ]
 [ 1.35361035 -0.35459047 -1.5333978   1.88660098 -0.34195706]
 [ 0.80491348 -1.45426459 -0.20730438 -1.41750882  0.28156436]
 [-0.38250591  1.12612056  1.55913737  1.53937741 -0.54585494]]


# 5.program to find common values between two arrays using numpy.

In [15]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(array1, array2)

print(common_values)


[3 4 5]


# 6.how to get the date of yestrday,today and tommrow in python

In [16]:
from datetime import datetime, timedelta

today = datetime.now()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)
today_str = today.strftime("%Y-%m-%d")
yesterday_str = yesterday.strftime("%Y-%m-%d")
tomorrow_str = tomorrow.strftime("%Y-%m-%d")

print("Yesterday:", yesterday_str)
print("Today:", today_str)
print("Tomorrow:", tomorrow_str)


Yesterday: 2023-09-24
Today: 2023-09-25
Tomorrow: 2023-09-26


# 7. Consider two random array A and B, check if they are equal

# 8.Create random vector of size 10 and replace the maximum value by 0

In [18]:
import numpy as np
rv = np.random.random(10)
rv[rv.argmax()]=0
rv

array([0.88501455, 0.15031704, 0.58150546, 0.78860081, 0.49621738,
       0.17701994, 0.59635347, 0.5048031 , 0.        , 0.42117912])

# 9. print all values of an array

In [19]:
for i in rv:
    print(i)

0.8850145501708937
0.1503170409525575
0.5815054588219445
0.7886008082581688
0.4962173798166989
0.17701993560195595
0.5963534689356264
0.5048031049275274
0.0
0.42117911663544905


# 10. sub mean of each row 

In [20]:
m =np.array([[1,2,3],
     [4,5,6],
      [7,8,9]])
mean=[]
for i in range(len(m)):
    mean.append(m[i:i+1].mean()) 
print(mean)
for i in range(len(mean)):
    m[i:i+1]=m[i:i+1]-mean[i]
print(m)

[2.0, 5.0, 8.0]
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]


# 11.consider a vec, add 1 to each ele index by 2nd vec


In [21]:
vec1 = np.array([1,2,3,4,5,6])
vec2 = np.array([4,1,1,8])

for i in vec2:
    if (i<len(vec1)):
        vec1[i]+=1
        
vec1

array([1, 4, 3, 4, 6, 6])

# 12. diagonal of a dot product

In [22]:
vec1 =np.array([[1,2,3],
     [4,5,6],
      [7,8,9]])
vec2 = np.array([[10,11,12],
                 [13,14,15],
                 [17,18,19]])

vec3 = np.dot(vec1,vec2)
np.diag(vec3)

array([ 87, 222, 375])

# 13.most freq value in an array

In [24]:
x= np.random.randint(0,10,50)
np.bincount(x).argmax()

8

# 14.n largest values 

In [25]:
n= int(input('enter a number: '))
ar = np.array([1,2,3,4,5,6])
ar.sort()
if(n<len(ar)):
    print(ar[-n:])
else:
    print('error')

enter a number: 5
[2 3 4 5 6]


# 15. create record array from regular array

In [26]:
a= np.array([(1, "vis", 22),
            (2, "ach", 23),
            (3, "lik", 22)],
            dtype=[('id', int), ('name', 'U10'), ('age', int)])
b = np.rec.array(a)

print("id:",b.id)
print("name:",b.name)
print("age:",b.age)

id: [1 2 3]
name: ['vis' 'ach' 'lik']
age: [22 23 22]


# 16. swap 2 rows of an array

In [27]:
a =np.array([[1,2,3],
     [4,5,6],
      [7,8,9]])
print(a)
a[[0,1]]=a[[1,0]]
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [1 2 3]
 [7 8 9]]


# 17. reshape to next dimen

In [28]:
a =np.array([[23,34,121],
     [23,22,67],
      [686,434,123]])

b=a.reshape((a.shape[0],a.shape[1],1))
b

array([[[ 23],
        [ 34],
        [121]],

       [[ 23],
        [ 22],
        [ 67]],

       [[686],
        [434],
        [123]]])